In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statistics import mean

In [2]:
train_df_path ="../../../physionet.org/files/chexchonet/1.0.0/metadata_train_90_split.csv"
test_df_path ="../../../physionet.org/files/chexchonet/1.0.0/metadata_test_90_split.csv"
val_df_path = "../../../physionet.org/files/chexchonet/1.0.0/metadata_eval_90_split.csv"

val_df = pd.read_csv(val_df_path)
train_df = pd.read_csv(train_df_path)
test_df = pd.read_csv(test_df_path)

In [3]:
WholeData = pd.concat([test_df, val_df, train_df], ignore_index=True)

In [4]:
WholeData.head()

,patient_id,cxr_filename,cxr_time_offset,cxr_year,cxr_path,cxr_pixel_spacing_x,cxr_pixel_spacing_y,age,sex,ivsd,lvpwd,lvidd,slvh,dlv,composite_slvh_dlv,heart_transplant,lung_transplant,pacemaker_or_icd
0,003d088d5ee2ab24c494bb1bf91df253,003d088d5ee2ab24c494bb1bf91df253_1c7b68b1.jpg,2636 days 18:01:59.142804,2017,./cxrs/003d088d5ee2ab24c494bb1bf91df253_1c7b68...,0.194556,0.194556,60,F,0.68429,0.693437,4.00847,0,0,0,0,0,0
1,003d088d5ee2ab24c494bb1bf91df253,003d088d5ee2ab24c494bb1bf91df253_cd7cd3cb.jpg,2811 days 16:18:59.142804,2017,./cxrs/003d088d5ee2ab24c494bb1bf91df253_cd7cd3...,0.194556,0.194556,61,F,0.68429,0.693437,4.00847,0,0,0,0,0,0
2,00632724788f0fbfc6a0dd0fd34adcc4,00632724788f0fbfc6a0dd0fd34adcc4_acf63c2f.jpg,4963 days 03:14:32.355690,2017,./cxrs/00632724788f0fbfc6a0dd0fd34adcc4_acf63c...,0.190200,0.190200,55,F,1.22507,1.212260,4.24297,0,0,0,0,0,0
3,006df813c0e688abf2ba90860ddad0de,006df813c0e688abf2ba90860ddad0de_ee03ea0f.jpg,3201 days 02:58:25.746936,2018,./cxrs/006df813c0e688abf2ba90860ddad0de_ee03ea...,0.194556,0.194556,85,F,1.42760,0.650349,4.41724,1,0,1,0,0,0
4,008bc839354564c5b16fc7cec3df8da9,008bc839354564c5b16fc7cec3df8da9_2436d8ff.jpg,3509 days 20:34:00.626676,2018,./cxrs/008bc839354564c5b16fc7cec3df8da9_2436d8...,0.194556,0.194556,47,M,1.28650,1.415680,9.28234,0,1,1,0,0,0

In [5]:
WholeDataX =WholeData.groupby("sex")
WholeDataX_df = WholeDataX.describe()
WholeDataX_df

    cxr_year                                                                 \
       count         mean       std     min     25%     50%     75%     max
sex
F    37289.0  2015.320658  1.619522  2012.0  2014.0  2015.0  2017.0  2018.0
M    34300.0  2015.304781  1.626336  2012.0  2014.0  2015.0  2017.0  2018.0

    cxr_pixel_spacing_x            ... lung_transplant      pacemaker_or_icd  \
                  count      mean  ...             75%  max            count
sex                                ...
F               37289.0  0.194291  ...             0.0  1.0          37289.0
M               34300.0  0.194287  ...             0.0  1.0          34300.0


        mean       std  min  25%  50%  75%  max
sex
F    0.05570  0.229345  0.0  0.0  0.0  0.0  1.0
M    0.08723  0.282176  0.0  0.0  0.0  0.0  1.0

[2 rows x 104 columns]

In [6]:
# Print the total number of images
print("Number of images:", len(WholeData))

# Count unique patients
unique_patients = WholeData['patient_id'].nunique()
print("Number of unique patients:", unique_patients)

Number of images: 71589
Number of unique patients: 24689

In [7]:
# Group data by sex and count occurrences
sex_counts = WholeData['sex'].value_counts()

# Calculate the total count of patients by sex to get percentages
total_counts = len(WholeData)

male_percent = 100 * sex_counts.get('M', 0) / total_counts
female_percent = 100 * sex_counts.get('F', 0) / total_counts

# Output results
print(sex_counts)
print("Male Percent: ", male_percent)
print("Female Percent: ", female_percent)
print("# Images:", total_counts)

sex
F    37289
M    34300
Name: count, dtype: int64
Male Percent:  47.912388774811774
Female Percent:  52.087611225188226
# Images: 71589

In [8]:
WholeData.columns

Index(['patient_id', 'cxr_filename', 'cxr_time_offset', 'cxr_year', 'cxr_path',
       'cxr_pixel_spacing_x', 'cxr_pixel_spacing_y', 'age', 'sex', 'ivsd',
       'lvpwd', 'lvidd', 'slvh', 'dlv', 'composite_slvh_dlv',
       'heart_transplant', 'lung_transplant', 'pacemaker_or_icd'],
      dtype='object')

In [9]:
WholeData_020= WholeData[(WholeData['age'] >= 0) & (WholeData['age'] <= 19)]
WholeData_2040= WholeData[(WholeData['age'] >= 20) & (WholeData['age'] <= 39)]
WholeData_4060= WholeData[(WholeData['age'] >= 40) & (WholeData['age'] <= 59)]
WholeData_6080= WholeData[(WholeData['age'] >= 60) & (WholeData['age'] <= 79)]
WholeData_80= WholeData[(WholeData['age'] >= 80) ]
totalAgeCXP=len(WholeData_020)+len(WholeData_2040)+len(WholeData_4060)+len(WholeData_6080)+len(WholeData_80)

In [10]:
print("'0-20' Percent:  ",100*len(WholeData_020)/totalAgeCXP)
print("'20-40' Percent:  ",100*len(WholeData_2040)/totalAgeCXP)
print("'40-60' Percent:  ",100*len(WholeData_4060)/totalAgeCXP)
print("'60-80' Percent:  ",100*len(WholeData_6080)/totalAgeCXP)
print("'80-' Percent:  ",100*len(WholeData_80)/totalAgeCXP)

'0-20' Percent:   0.16482979228652447
'20-40' Percent:   11.128804704633394
'40-60' Percent:   26.94687731355376
'60-80' Percent:   48.053471902107866
'80-' Percent:   13.706016287418459

AUC over 5 runs

In [11]:
Eval1 = pd.read_pickle("./results/results9/ret_mets_test_results_9.csv_updated.pkl")
Eval2 = pd.read_pickle("./results/results21/ret_mets_test_results_21.csv_updated.pkl")
Eval3 = pd.read_pickle("./results/results25/ret_mets_test_results_25.csv_updated.pkl")
Eval4 = pd.read_pickle("./results/results35/ret_mets_test_results_35.csv_updated.pkl")
Eval5 = pd.read_pickle("./results/results42/ret_mets_test_results_42.csv_updated.pkl")

In [12]:
evals = [Eval1, Eval2, Eval3, Eval4, Eval5]

# Initialize DataFrame
# Assuming each eval has the same set of metrics
metrics = list(evals[0]['ret_met'].keys()) + ['no finding']  # Adding 'No Finding' as a separate metric
columns = [f'auc{i+1}' for i in range(len(evals))]  # Generate column names
Evalall = pd.DataFrame(index=metrics, columns=columns)  # Use metrics as index
EvalallAuprc = pd.DataFrame(index=metrics, columns=[f'auprc{i+1}' for i in range(len(evals))])  # Use metrics as index

# Populate AUC values
for j, eval_data in enumerate(evals, start=1):
    for metric, values in eval_data['ret_met'].items():
        auc_value = values['auroc'][0]  # Using 'auroc' tuple's first element
        auprc_value = values['auprc'][0]  # Using 'auroc' tuple's first element
        Evalall.at[metric, f'auc{j}'] = auc_value
        EvalallAuprc.at[metric, f'auprc{j}'] = auprc_value
        if metric == 'composite':
            # Calculate and store "No Finding" AUC as 1 minus the "Composite" AUC
            Evalall.at['no finding', f'auc{j}'] = 1 - auc_value
            EvalallAuprc.at['no finding', f'auprc{j}'] = 1 - auprc_value

# Convert all AUC columns to numeric and round
Evalall.iloc[:, 1:] = Evalall.iloc[:, 1:].apply(pd.to_numeric).round(3)
EvalallAuprc.iloc[:, 1:] = EvalallAuprc.iloc[:, 1:].apply(pd.to_numeric).round(3)

In [13]:
Evalall

                auc1   auc2   auc3   auc4   auc5
slvh        0.444346  0.424  0.548  0.492  0.475
dlv         0.498758    0.5    0.5  0.487    0.5
composite   0.482618  0.469  0.526  0.486  0.484
no finding  0.517382  0.531  0.474  0.514  0.516

In [14]:
EvalallAuprc

              auprc1 auprc2 auprc3 auprc4 auprc5
slvh        0.107384  0.091  0.102  0.101  0.087
dlv         0.053482  0.053  0.093  0.057  0.054
composite   0.165186  0.141  0.175  0.136   0.13
no finding  0.834814  0.859  0.825  0.864   0.87

In [20]:
def log_stats(eval_1, eval_name):
    print(f'ALL Mean of 4 {eval_name} mean over 5 run: {round(eval_1.mean(axis=0).mean(),3)}')
    print(f'ALL Confidence interval of 4 {eval_name} mean over 5 run: {round(1.96 * eval_1.mean(axis=0).std()/np.sqrt(5) ,3 )}')
    print(f'ALL Mean of {eval_name} per disease over 5 run:\n{round(eval_1.mean(axis=1),3)}')
    print(f"ALL Confidence interval of {eval_name} per disease over 5 run:\n{round(1.96 * eval_1.std(axis=1)/ np.sqrt(5),3)}")

In [21]:
log_stats(Evalall, "AUC")

ALL Mean of 4 AUC mean over 5 run: 0.493
ALL Confidence interval of 4 AUC mean over 5 run: 0.01
ALL Mean of AUC per disease over 5 run:
slvh          0.476669
dlv           0.497152
composite     0.489524
no finding    0.510476
dtype: object
ALL Confidence interval of AUC per disease over 5 run:
slvh          0.041911
dlv           0.004997
composite     0.018812
no finding    0.018812
dtype: object

In [22]:
log_stats(EvalallAuprc, "AUPRC")

ALL Mean of 4 AUPRC mean over 5 run: 0.29
ALL Confidence interval of 4 AUPRC mean over 5 run: 0.005
ALL Mean of AUPRC per disease over 5 run:
slvh          0.097677
dlv           0.062096
composite     0.149437
no finding    0.850563
dtype: object
ALL Confidence interval of AUPRC per disease over 5 run:
slvh          0.007367
dlv           0.015204
composite     0.017149
no finding    0.017149
dtype: object